### PR TITLE
(WIP) Karma

### PR DESCRIPTION
**Pull request by melwil**
Added a plugin to keep track of karma for people.
- [x] Make karma plugin.
- [x] Add logging for each movement in karma.

### CODE REVIEW

**Comment by espenja** [comment]
What is this supposed to do exactly? Maybe fill in about the intentions for this plugin.

**Comment by melwil** [comment]
The point of the plugin will be abundantly clear when it starts being used. It allows people to give and take points from each other, so that each person can get a score which symbolizes how they contribute to a channel.

If I help someone, post a cool link or do something nice, people can increase my karma. If I misbehave, they can take it away.

**Comment by melwil** [comment]
All that being said, don't merge this yet, I need to tinker a bit more with it. I thought of some problems while I was sleeping :p

**Comment by espenja** [comment]
This is IRC! THIS IS STACKOVERFLOW!

**Comment by melwil** [comment]
It's a concept I've seen on irc way before stackoverflow was even a thing, but it kind of works like that, yes.

**Pull request merged**
